"""
Notification Service — Email (SMTP) and WhatsApp link generation.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import streamlit as st
import urllib.parse


def send_email_alert(
    recipient: str,
    subject: str,
    body: str,
    smtp_server: str = None,
    smtp_port: int = None,
    sender_email: str = None,
    sender_password: str = None,
) -> tuple[bool, str]:
    """
    Send an email alert via SMTP.

    Returns:
        (success: bool, message: str)
    """
    try:
        # Use secrets if not provided
        cfg = st.secrets.get("email", {})
        smtp_server = smtp_server or cfg.get("smtp_server", "smtp.gmail.com")
        smtp_port = smtp_port or cfg.get("smtp_port", 587)
        sender_email = sender_email or cfg.get("sender", "")
        sender_password = sender_password or cfg.get("password", "")

        if not sender_email or not sender_password:
            return False, "Email credentials not configured. Set them in .streamlit/secrets.toml."

        msg = MIMEMultipart()
        msg["From"] = sender_email
        msg["To"] = recipient
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "html"))

        with smtplib.SMTP(smtp_server, smtp_port, timeout=15) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, recipient, msg.as_string())

        return True, f"✅ Email sent to {recipient}"
    except smtplib.SMTPAuthenticationError:
        return False, "❌ Authentication failed. Check email credentials."
    except smtplib.SMTPException as e:
        return False, f"❌ SMTP error: {e}"
    except Exception as e:
        return False, f"❌ Failed to send email: {e}"


def generate_whatsapp_link(phone: str, message: str) -> str:
    """
    Generate a WhatsApp deep link (wa.me) for sending a message.

    Args:
        phone: Phone number with country code (e.g., "919876543210")
        message: Text message to pre-fill
    """
    encoded_message = urllib.parse.quote(message)
    # Strip any non-digit characters from phone
    phone_digits = "".join(filter(str.isdigit, phone))
    return f"https://wa.me/{phone_digits}?text={encoded_message}"


def format_alert_email(project_name: str, risk_level: str, progress: dict, recommendations: list) -> str:
    """Format an HTML email body with project alert details."""
    rec_html = ""
    for rec in recommendations[:5]:
        rec_html += f"""
        <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">{rec['priority']}</td>
            <td style="padding: 8px; border: 1px solid #ddd;">{rec['category']}</td>
            <td style="padding: 8px; border: 1px solid #ddd;">{rec['action']}</td>
        </tr>
        """

    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #1E88E5;">🏗️ Project Alert — {project_name}</h2>
        <hr>

        <h3>📊 Status Summary</h3>
        <ul>
            <li><b>Risk Level:</b> {risk_level}</li>
            <li><b>Budget Used:</b> {progress.get('cost_progress_pct', 0):.0f}%</li>
            <li><b>Time Elapsed:</b> {progress.get('time_progress_pct', 0):.0f}%</li>
            <li><b>Days Remaining:</b> {progress.get('days_remaining', 'N/A')}</li>
            <li><b>Total Spent:</b> ₹{progress.get('total_spent', 0):,.0f}</li>
            <li><b>Budget:</b> ₹{progress.get('total_budget', 0):,.0f}</li>
        </ul>

        <h3>🤖 AI Recommendations</h3>
        <table style="border-collapse: collapse; width: 100%;">
            <tr style="background: #1E88E5; color: white;">
                <th style="padding: 8px; border: 1px solid #ddd;">Priority</th>
                <th style="padding: 8px; border: 1px solid #ddd;">Category</th>
                <th style="padding: 8px; border: 1px solid #ddd;">Action</th>
            </tr>
            {rec_html}
        </table>

        <br>
        <p style="color: #888; font-size: 12px;">
            — Generated by Agentic AI Construction POC | Nikitha Build Tech
        </p>
    </body>
    </html>
    """


def format_whatsapp_message(project_name: str, risk_level: str, progress: dict) -> str:
    """Format a WhatsApp alert message."""
    return (
        f"🏗️ *PROJECT ALERT*\n\n"
        f"📌 *{project_name}*\n"
        f"⚠️ Risk Level: {risk_level}\n"
        f"💰 Budget Used: {progress.get('cost_progress_pct', 0):.0f}%\n"
        f"⏱️ Time Elapsed: {progress.get('time_progress_pct', 0):.0f}%\n"
        f"📅 Days Remaining: {progress.get('days_remaining', 'N/A')}\n"
        f"💸 Total Spent: ₹{progress.get('total_spent', 0):,.0f}\n\n"
        f"— Agentic AI | Nikitha Build Tech"
    )
